In [1]:
import numpy as np

***markdown***

In [2]:
array=np.array([1,2,3]) #declaring np array

In [3]:
array_with_datasize=np.array([1,2,3],np.int8)

In [4]:
array

array([1, 2, 3])

In [5]:
array[1]

2

In [6]:
array[0]

1

In [16]:
np.array({23,23,24}) #can make from set too but dtype is object

array([23, 23, 24], dtype=int8)

# Important np array functons

**(1) shape gives the (row,column)**

In [7]:
array.shape

(3,)

In [8]:
multi_array_2=np.array([[1,2,3],[4,5,6]])

In [9]:
multi_array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
multi_array_2.shape

(2, 3)

**(2) dtype gives the datatype of np array elements**

In [12]:
array.dtype

dtype('int64')

In [13]:
array_with_datasize.dtype

dtype('int8')

**(3) reshape it changes the shape of an array.The number of elements will remain same**

In [17]:
multi_array_2.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

**(4) ravel will make the array 1D array**

In [18]:
multi_array_2.ravel()

array([1, 2, 3, 4, 5, 6])

**(5) argmax Returns the indices of the maximum values along an axis.
  (6) argmin Returns the indices of the minimum values along an axis.**

**(7)copy:If we copy numpy array like normal variable then the original variable also changes.Therefore we use copy function**

**(8)Vertical Stack: vstack() connects arrays of with same no of columns vertically**

In [71]:
ar1=np.array((1,2,3))
ar2=np.array((4,5,6))

np.vstack((ar1,ar2))

array([[1, 2, 3],
       [4, 5, 6]])

**(9)Horizontal Stack: hstack() connects arrays of with same no of columns vertically**

In [72]:
hr1=np.array([[1,2],
              [3,4]])
hr2=np.array([[11,22],
              [34,43]])
np.hstack((hr1,hr2))

array([[ 1,  2, 11, 22],
       [ 3,  4, 34, 43]])

# Axis

**Axis0 corresponds to down the columns Axis1 corresponds to right the row**

In [23]:
array.sum(axis=0) 

6

In [27]:
multi_array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
multi_array_2.sum(axis=0)

array([5, 7, 9])

In [30]:
multi_array_2.sum(axis=1)

array([ 6, 15])

# Accessing rows and column

# array[rowStart:rowEnd(excluded) ,columnStart:columnEnd(excluded)]

In [35]:
multi_array_2[:,1:2]

array([[2],
       [5]])

In [42]:
multi_array_2[0:1,:-1]

array([[1, 2]])

# PRACTISE:draw a 5x5 matrix with 1 at borders and 0 everywhere else with 9 at centre

In [63]:
newar=np.ones((5,5))

In [66]:
newar[1:-1,1:-1]=0

In [68]:
newar[2][2]=9

In [69]:
newar

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### We can index numpy array with list ie multiple values(also with true and false)

In [73]:
multi_array_2

array([[1, 1, 1],
       [4, 5, 6]])

In [81]:
multi_array_2[[0,1],[0,2]]

array([1, 6])